include /etc/openldap/schema/core.schema
include /etc/openldap/schema/cosine.schema
include /etc/openldap/schema/inetorgperson.schema
include /etc/openldap/schema/nis.schema
include /etc/openldap/schema/openldap.schema

pidfile /run/openldap/slapd.pid
argsfile /run/openldap/slapd.args

modulepath /usr/lib/openldap
moduleload back_mdb.so

database mdb
maxsize 1073741824
suffix "${LDAP_BASE_DN}"
rootdn "cn=admin,${LDAP_BASE_DN}"
rootpw "${LDAP_ADMIN_PASSWORD_HASH}"
directory /var/lib/openldap/openldap-data

index objectClass eq
index uid eq
index cn,sn,mail pres,eq,sub
index member eq

access to attrs=userPassword
    by self write
    by anonymous auth
    by * none

access to *
    by self write
    by * read
