# Data Source
spring.datasource.url=${JDBC_DATABASE_URL\:jdbc\:sqlserver\://localhost;databaseName\=scl}
spring.datasource.username=${JDBC_DATABASE_USERNAME\:sa}
spring.datasource.password=${JDBC_DATABASE_PASSWORD\:<<YOUR_PASSWORD>>}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.jpa.properties.hibernate.types.print.banner=false

# E-mail
spring.mail.host=${SMTP_HOST\:smtp.freesmtpservers.com}
spring.mail.username=${SMTP_USERNAME\:<<YOUR_USERNAME>>}
spring.mail.password=${SMTP_PASSWORD\:<<YOUR_PASSWORD>>}
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=45000
app.mail.from=scl@ampliar.com.br
app.mail.displayName=SCL
formsSecurityConfig.rememberMeKey=427E316F34

# Spring MVC
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd'T'HH\:mm\:ss
spring.mvc.format.time=HH\:mm\:ss

# File Upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-part-count=100

# Actuators
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

app.baseHost=${BASE_HOST\:http\://localhost\:8081}