# Data Source
spring.datasource.url=jdbc:sqlserver://${JDBC_DATABASE_HOST};databaseName=${JDBC_DATABASE_DB};trustServerCertificate=true
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.jpa.properties.hibernate.types.print.banner=false
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_aud
spring.jpa.properties.org.hibernate.envers.revision_field_name=id_revision
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=id_revision_type

# E-mail
spring.mail.host=${SMTP_HOST}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=45000
app.mail.from=scl@ampliar.com.br
app.mail.displayName=SCL

# Spring MVC
spring.web.locale=en_US
spring.web.locale-resolver=fixed
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd'T'HH\:mm\:ss
spring.mvc.format.time=HH\:mm\:ss

# File Upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-part-count=100

# Actuators
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Others
app.baseHost=${BASE_HOST\:http\://localhost\:8080}
formsSecurityConfig.rememberMeKey=427E316F34
