package ludo.mentis.aciem.scl.model;


public enum FxSettlementStepType {

    INSTRUCTION_RECEIVED,
    SUBCUSTODIAN_APPROVAL,
    RECEIVED_OR_PAID_FOREIGN_CURRENCY,
    RECEIVED_OR_PAID_LOCAL_CURRENCY,
    UPSTREAM_RELEASE_OR_CONFIRMATION

}
